site_name: Swiftshadow


plugins:
    - mkdocstrings
    - search

nav:
    - Introduction: index.md
    - Getting Started: getting-started.md
    - Reference: references.md
    - Proxy Providers: providers.md

repo_url: https://github.com/sachin-sankar/swiftshadow
repo_name: sachin-sankar/swiftshadow
copyright: Copyright &copy; 2023 - 2024 Sachin Sankar
extra:
  generator: false


theme:
  name: material
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.footer
    - content.code.copy
    - content.code.select
  
  palette:
    primary: deep purple
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

docs_dir : docs-src
site_dir : docs